[package]
name = "am-algorithm"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unicode-normalization = "0.1"
unicode_categories = "0.1"
regex = "1.0"